auth0:
  audience: https://ing-sis-org-snippets
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-7qnoj6g0bvw3f2qs.us.auth0.com/

logging:
  level:
    org:
      springframework:
        security: DEBUG